version: '3'

services:

  #### MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      timeout: 5s
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=study
    volumes:
      - ./data/mysql/:/var/lib/mysql
      - ./data/my.cnf:/etc/mysql/my.cnf

networks:
  default:
    driver: bridge
