spring:
  application.name: spring-sse
  profiles:
    active: local
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: core-db-pool
      maximum-pool-size: 10
      connection-timeout: 10000
      max-lifetime: 60000
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC
      hibernate.default_batch_fetch_size: 100

---
spring.config.activate.on-profile: local

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/study?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password: root

  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        timezone.default_storage: NORMALIZE_UTC
        jdbc.time_zone: UTC
        format_sql: true
        show_sql: true